[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "deepseek-api"
dependencies = [
    "requests",
    "numpy",
    "wasmtime"
]
dynamic = ["version"]

[tool.hatch.version]
source = "vcs"